platform :ios, '8.0'
swift_version = '3.0'
use_frameworks!

target 'UIViewVisibility_Example' do
  pod 'UIViewVisibility', :path => '../'

  target 'UIViewVisibility_Tests' do
    inherit! :search_paths

  pod 'Quick'
  pod 'Nimble'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
