use_frameworks!

target 'UIViewVisibility_Example' do
  pod 'UIViewVisibility', :path => '../'

  target 'UIViewVisibility_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
